### ISSUE TITLE
unset

### ISSUE THREAD

**Issue by dextel2** [bradtraversy/phploginapp#2]
https://github.com/bradtraversy/phploginapp/blob/31f5a1bbf9a6db61587d32d4fbccda5985761425/register.php#L42

I do not understand the concept of it.

**Comment by PurushothamanSrikanth** [comment]
> https://github.com/bradtraversy/phploginapp/blob/31f5a1bbf9a6db61587d32d4fbccda5985761425/register.php#L42
> 
> I do not understand the concept of it.

@dextel2 This [link](https://www.php.net/manual/en/function.unset.php) might help you.
